@startuml
left to right direction
skinparam packageStyle rect
actor менеджер_тестирования
actor клиент_тестирования
rectangle тест {
  менеджер_тестирования-- (запустить тест)
  менеджер_тестирования-- (сформировать результаты)
  менеджер_тестирования-- (сформировать отчёт)
  (начать тест) .> (запустить тест)
  (запустить тест) .> (пройти тест)
  (сформировать результаты) .> (сформировать отчёт)
  (сформировать отчёт) .> (получить результаты)
  клиент_тестирования -- (начать тест)
  клиент_тестирования -- (пройти тест)
  клиент_тестирования -- (получить результаты)
}
@enduml